yaml
name: moopy CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  main:
    runs-on: fedora-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run tests
      run: pytest